### ISSUE TITLE
streaming_search() -> iterator

### ISSUE THREAD

**Issue by Heiko-Zelt** [inejge/ldap3#114]
Hello guys,

I need to map the result entries of a streaming_search(). I am new to rust/tokio and the ldap3 crate. I wonder, why doesn't streaming_search() return an iterator? So it would be easy to use in a for-in-loop or to map(), filter(), collect() the results.

Or how could I map the results or convert [SearchStream](https://docs.rs/ldap3/latest/ldap3/struct.SearchStream.html#) into an iterator? Is there a code example?

Kind regards
Heiko

**Comment by inejge** [comment]
Async iterators as such are still an unresolved question on the language level (see rust-lang/rust#79024). Search streams in LDAP are a simpler use case, but I wouldn't like to tie the library to some construct which might be incompatible with a later solution. Future directions notwithstanding, `SearchStream` can't be integrated with a regular iterator because its methods are async.
