### ISSUE TITLE
tokio-core is deprecated.

### ISSUE THREAD

**Issue by quadrupleslap** [inejge/ldap3#29]

**Comment by bbigras** [comment]
Any progress on this?

**Comment by inejge** [comment]
Just a short note (as I otherwise don't have the time to work on this library): moving away from `tokio_core` to `tokio` would have to account for the use of the former in `tokio_proto`, also deprecated but unfortunately the foundation of `ldap3`. I don't see a straightforward way to excise `tokio_proto` without a massive rewrite of this crate's internals.

**Comment by masonk** [comment]
Yes, I was realizing that last night when I was trying to do the migration myself.

**Comment by nevi-me** [comment]
Hi @inejge , I had a go at trying to port to tokio today, and have made some progress. It looks like the blocker is `tokio_proto` more than anything, for the multiplex tcp connections.

I'm due to release a program that will be deployed at clients in the coming days, so I don't have a choice but to "make it work".
I'm going to try something from the tower ecosystem and see if it works. I'll provide feedback in a few days

**Comment by inejge** [comment]
Right, the `tokio_proto` multiplexer is the tricky part, and having it available is what made initial development comparatively straightforward. For your immediate problem, I'd recommend starting a dedicated thread for LDAP connection(s), with its own `tokio_core` event loop, and communicating with the rest of the system via oneshot/mpsc channels. I believe these can work across `tokio` flavors.

**Comment by nevi-me** [comment]
I found https://github.com/red75prime/tokio-proto/commit/cd1af828791fcd60dc518eb713a53d00e9aacf91, which while not ideal, still allowed me to get the crate to build. I just got it to build now actually.

**Comment by inejge** [comment]
With the port to Tokio 0.2, this can now be closed.

**Comment by nevi-me** [comment]
Thanks @inejge
