### ISSUE TITLE
What is the purpose of drive()?

### ISSUE THREAD

**Issue by andrewbanchich** [inejge/ldap3#53]
I'm confused about why this is necessary. Shouldn't whatever runtime you're using poll the Future to completion just like any other Future?

**Comment by inejge** [comment]
Since LDAP is a multiplexed protocol, I saw the separation of the connection (`LdapConnAsync`) and the handles (`Ldap`) as the most straightforward implementation strategy. Making the separation visible and explicit ought to make managing the connection lifecycle more flexible, without being too much of an ergonomic burden.

**Comment by andrewbanchich** [comment]
Okay, thanks for clarifying!
