### ISSUE TITLE
[Question] OPT_REFERRALS

### ISSUE THREAD

**Issue by Dzordzu** [inejge/ldap3#95]
How to enable option that is similar to the OPT_REFERRALS in the python libraries?

**Comment by inejge** [comment]
You can't, since there is no referral chasing support in the library, and I don't plan to add it. Referral chasing is woefully underspecified, especially regarding the security properties of further connections, and IMO is best handled through environment-specific code.

The adapter framework supplied by the crate should be sufficient to implement referral chasing, and I'm interested in any deficiencies encountered in such an implementation, but I'm not going to write it myself.
